Fixed some path duplication issues

diff --git a/bin/aws-sts b/bin/aws-sts
--- a/bin/aws-sts
+++ b/bin/aws-sts
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 err() {
-    echo $1
+    echo $1 >&2
     exit 1
 }
 
@@ -9,8 +9,11 @@ which aws > /dev/null || err "Could not find aws in path."
 [[ $# -lt 1 ]] && err "Usage: $(basename $0) <tokencode>"
 
 accountid=${AWS_ACCOUNT_ID:-${2:-324842975178}}
-AWS_SESSION_TOKEN=`aws sts get-session-token --serial-number arn:aws:iam::$accountid:mfa/jared --token-code $1|jq -r '.Credentials.SessionToken'`
+response=`aws sts get-session-token --serial-number arn:aws:iam::$accountid:mfa/$USER --token-code $1` || err "Error retrieving token. Token not set."
+aws_session_token=`echo $response|jq -r '.Credentials.SessionToken'`
+expiration=`echo $response|jq -r '.Credentials.Expiration'`
 
-echo $AWS_SESSION_TOKEN
-export $AWS_SESSION_TOKEN
+echo "AWS_SESSION_TOKEN=$aws_session_token"
+echo "export AWS_SESSION_TOKEN;"
+echo "echo Session expires at $expiration"
 
